### PR TITLE
Example how to plot energy graph with Dash

### PR DESCRIPTION
**Pull request by AndreasWunsch**
We have added a jupyter notebook to demonstrate how to create interactive OEMOF system graphs with [Plotly-Dash](https://dash.plotly.com/). We would be happy to share this with the OEMOF community as it turned out to be a very useful functionality.

### CODE REVIEW

**Comment by p-snft** [comment]
Thank you, this is pretty neat. Though, I don't know if it should be merged here. Actually, we considered closing this repository as examples are moved to the respective packages and was not updated for years. Maybe, this can be evolved to a standard plotting option in [oemof.visio](https://github.com/oemof/oemof-visio). (The package could also need some love, but it's a better candidate to be updated rather than closed. Why not kick it off with something shiny?)

A second option I see, is having a Tutorial/"How to" blog post at [oemof.org](https://oemof.org). This would be a new way for us to present example code bit it might work out well. Note that these options are not mutually exclusive. Both can be combined.

@oemof-developer: What do you think?

**Comment by AndreasWunsch** [comment]
The blog post option sounds nice and would be a fast and easy way to publish this. We also thought of writing a short medium.com article about it, so a similar idea like your blog post suggestion.

**Comment by AndreasWunsch** [comment]
Hi all, any news on this topic?

**Comment by p-snft** [comment]
Thanks for the reminder. We just talked about the topic and think an efficient way to do this is using [gist](https://gist.github.com) for the code additionally to the blog post.

I would like to use the example also as new a way to present examples at the upcoming oemof meeting (20th of November) if this is okay for you.

**Comment by p-snft** [comment]
Comment for those interested in the example: It moved to https://gitlab.cc-asp.fraunhofer.de/-/snippets/1016.

**Pull request closed without merging**
