### PR TITLE
Adapt variable chp example

### PR DESCRIPTION
**Pull request by uvchik**
Adapt variable CHP example

### CODE REVIEW

**Comment by uvchik** [comment]
I think you do not have to adapt the i/o-plot. Add a standardised pandas plot or remove plots at all.

Alternatively we can just compare the two sums in a formatted print statement.

I created a new folder with (special) plotting examples with `oemof-visio`.

**Comment by s3pp** [comment]
Ah, I see, I see, thank you for your comment, I threw out my earlier commits and implemented your work of variable_chp_plot.py in variable_chp.old.py. On the premise, that a new dependency to oemof_visio is fine : ), it works. Except I still have to make the plot_only condition work again.

**Comment by uvchik** [comment]
You should keep in mind, that the old example was made for different purposes. I will have a look soon and give you a feedback.

**Comment by uvchik** [comment]
I removed the main functions because some users find it easier that way. Therefore the change file may look confusing - sorry.

As I wrote above the example was used for tests so I removed everything that is not needed any more. Guess this was much easier for me because I knew the former usage 😄

Furthermore I made the oemof-visio package optional and added a simple bar plot if oemof-visio is not installed.

You can clean the example (comments, layout,..) as you like and merge afterwards.

**Comment by uvchik** [comment]
Would you remove everything except one python file and the csv-file.

**Comment by s3pp** [comment]
I read through your changes, but I made no further changes w.r.t comments and layout. I think everything is fine now! Just fixed shape_legend, that reverse attribute is working.

**Comment by uvchik** [comment]
@s3pp Thank you for your work 🎉

**Pull request merged**
