### PR TITLE
Start up costs & min/max runtimes

### PR DESCRIPTION
**Pull request by ckaldemeyer**
This provides examples on how to use start up costs and min/max runtimes.

### CODE REVIEW

**Comment by ckaldemeyer** [comment]
The review goes along with PR https://github.com/oemof/oemof/pull/446.

**Comment by ckaldemeyer** [comment]
> @ckaldemeyer ckaldemeyer changed the base branch from master to dev just now

Just to remain in the workflow..

**Comment by jnnr** [comment]
Thanks for your contribution! Its a nice feature. I tested the examples and they look fine. Only three remarks/questions:
* startup_shutdown.py: The demand profile in data.csv should include one period in time where the demand stays up for longer than 3 hours. In that case, the powerplant with cheaper variable cost but higher startup/shutdown cost starts contributing. I adapted that and could push it, if you are ok?
* min_max_runtimes.py: A question: Does `initial_status=1`mean that the actual value is one or that the powerplant is running? Seems to be the latter. Also, is there any constraint or something that causes to run the 'expensive_powerplant' at the final timestep. In the plot I get, it runs again after shutdown and without demand.
* Why are the plants called cheap and expensive if they have the same variable cost?

**Comment by ckaldemeyer** [comment]
> startup_shutdown.py: The demand profile in data.csv should include one period in time where the demand stays up for longer than 3 hours. In that case, the powerplant with cheaper variable cost but higher startup/shutdown cost starts contributing. I adapted that and could push it, if you are ok?

Yep. Thanks!

> min_max_runtimes.py: A question: Does initial_status=1mean that the actual value equals one or that the powerplant is running? Seems to be the latter.

Yes, it is the latter.

> Also, is there any constraint or something that causes to run the 'expensive_powerplant' at the final timestep. In the plot I get, it runs again after shutdown and without demand.

The initial status is also set in the end as explained in the docstring:

+        (0 = off, 1 = on). For minimum up and downtimes, the initial status
+        is set for the respective values in the edge regions e.g. if a
+        minimum uptime of four timesteps is defined, the initial status is
+        fixed for the four first and last timesteps of the optimization period.

Should we adapt the naming or is it o.k. like this!?

> Why are the plants called cheap and expensive if they have the same variable cost?

I just made that up quickly. Do you have suggestions!? Go ahead ;-)

**Comment by ckaldemeyer** [comment]
Thanks for your suggestions and review!

**Comment by ckaldemeyer** [comment]
> startup_shutdown.py: The demand profile in data.csv should include one period in time where the demand stays up for longer than 3 hours. In that case, the powerplant with cheaper variable cost but higher startup/shutdown cost starts contributing. I adapted that and could push it, if you are ok?
> 
> Yep. Thanks!
> 
>     min_max_runtimes.py: A question: Does initial_status=1mean that the actual value equals one or that the powerplant is running? Seems to be the latter.
> 
> Yes, it is the latter.
> 
>     Also, is there any constraint or something that causes to run the 'expensive_powerplant' at the final timestep. In the plot I get, it runs again after shutdown and without demand.
> 
> The initial status is also set in the end as explained in the docstring:
> 
>     (0 = off, 1 = on). For minimum up and downtimes, the initial status
>     is set for the respective values in the edge regions e.g. if a
>     minimum uptime of four timesteps is defined, the initial status is
>     fixed for the four first and last timesteps of the optimization period.
> 
> Should we adapt the naming or is it o.k. like this!?
> 
>     Why are the plants called cheap and expensive if they have the same variable cost?
> 
> I just made that up quickly. Do you have suggestions!? Go ahead ;-)

I have now merged the functionality into the dev.

@jnnr @uvchik : Feel free to change as you like and merge afterwards if you are fine!

**Comment by uvchik** [comment]
It is just an example and if it works and looks okay we can merge it.

**Comment by ckaldemeyer** [comment]
> It is just an example and if it works and looks okay we can merge it.

If @jnnr has naming improvements, he can change it directly! I am fine with it anyway..

**Pull request merged**
