### PR TITLE
Add readme and setup.py

### PR DESCRIPTION
**Pull request by birgits**
@gnn could you please have a look at the setup.py. The extras_require works and all necessary packages for examples of oemof_0.1 are installed. I will check oemof_0.2 once all examples are adapted and oemof 0.2.0 is ready.
@uvchik please have a look at the README and let me know if anything is missing.

### CODE REVIEW

**Comment by uvchik** [comment]
> @uvchik please have a look at the README and let me know if anything is missing.

I would remove everything that is already explained in the oemof readme to make it easier to maintain in the future. Otherwise all changes has to be done here and there.

My proposal:
To install a specific version use e.g. `pip install oemof==0.x.y` for further information about oemof see /link/. 
You may add [...] for further information about oemof (documentation, citation, license...) see /link/ [...] but I am not sure about that.

We could also add the versions in the header of each example. Than you use '=' '>' '<' for your specific example e.g. (Use pip install oemof<0.2.0 to run this example).

I would to have a TOC for each version but I do not know if there is a way do it automatically.

TOC of main Topics (installation, oemof 0.1.x, oemof 0.2.x,..)

### Installation
something

### oemof 0.1.x

TOC of all v0.1.x examples

**example 1**
Description

**example 2**
Description

### oemof 0.2.x

TOC of all v0.2.x examples

**example 1**
Description

**example 2**
Description


In this structure the description could be one sentence or three sentences or even an image if you like and everybody who adds an example is responsible to add a least one sentence.

@birgits What do you think?

**Comment by birgits** [comment]
Thank you @uvchik for your comments!

> I would remove everything that is already explained in the oemof readme to make it easier to maintain in the future. Otherwise all changes has to be done here and there.

I agree! I wouldn't take out the license part though and add a link to the oemof documentation.

> We could also add the versions in the header of each example. Than you use '=' '>' '<' for your specific example e.g. (Use pip install oemof<0.2.0 to run this example).

This sounds like a good solution and makes it very clear which example will work with which oemof release. On the other hand we'd have to update the examples for each minor release. And do you vote against the extras_require in setup.py then? @gnn which solution would you prefer? I find it very comfortable to install everything at once using the extras_require option. Maybe we could have both.

**Comment by uvchik** [comment]
> This sounds like a good solution and makes it very clear which example will work with which oemof release.

We could do that for all v0.1.x examples because they will work with `pip install oemof==0.1.4`. The v0.2.x examples will work with `pip install oemof`. Once we release v0.3.0 we have to change all examples in the v0.2.0 folder to the last v0.2.x release. So we have to change the line only once.

> I find it very comfortable to install everything at once using the extras_require option. Maybe we could have both.
I do not like it because I would not install the example repository at all. I would clone the repository and install oemof. So for me the easiest way to do it (minimal maintenance costs) is the following:

"Clone the repository (see https://help.github.com/articles/cloning-a-repository/) and install oemof (see https://github.com/oemof/oemof). If you want to install a specific version use `pip install oemof=x.y.z`"

The last sentence could be even moved to the oemof/oemof repository.

**Comment by uvchik** [comment]
the text could be nicer, I just wanted to explain the main idea.

**Comment by birgits** [comment]
> I do not like it because I would not install the example repository at all. I would clone the repository and install oemof.

I think a setup.py is a good idea because additional packages are needed such as matplotlib and perspectively maybe others (e.g. feedinlib?).

> We could do that for all v0.1.x examples because they will work with pip install oemof==0.1.4. The v0.2.x examples will work with pip install oemof. Once we release v0.3.0 we have to change all examples in the v0.2.0 folder to the last v0.2.x release. So we have to change the line only once.

:thumbsup:

**Comment by uvchik** [comment]
> I think a setup.py is a good idea because additional packages are needed such as matplotlib and perspectively maybe others (e.g. feedinlib?).

But in my opinion this should be handled in each example. For one example we need the xlrd package another needs the networkx package a third one jupiter and the next one scipy. For me it is far to complicated to handle this centrally.

**Comment by birgits** [comment]
> But in my opinion this should be handled in each example. For one example we need the xlrd package another needs the networkx package a third one jupiter and the next one scipy. For me it is far to complicated to handle this centrally.

Okay, I'll add this to the examples, adapt the README and delete setup.py. 
@gnn no need for your review of setup.py anymore ;)

**Comment by uvchik** [comment]
Maybe we should add a "How to add an example" section and write down what should be part of the example docstring (oemof version, needed packages,...),

**Comment by birgits** [comment]
@uvchik what's your opinion on the new README?

**Comment by uvchik** [comment]
I fixed the merge conflict because it was me who produced them.

**Comment by birgits** [comment]
Btw, can we merge this?

**Comment by uvchik** [comment]
It's up to you, I approved already :+1:

**Pull request merged**
